/**
 * Share an exported HTML document via the native share sheet.
 *
 * Behaviour:
 *  - If the platform supports Web Share with files, share the file directly.
 *  - If file-share is unsupported but navigator.share exists, share metadata
 *    (title only) so the share sheet still opens — no silent download.
 *  - Only fall back to a download when navigator.share is entirely missing
 *    or the share call throws a non-cancellation error.
 *
 * Important:
 *  - This does NOT send anything from the backend.
 *  - This does NOT create any "send" log or record.
 *  - The HTML is generated by the existing locked export renderer.
 */

export type ShareResult = 'shared' | 'cancelled' | 'downloaded' | 'unsupported' | 'failed';

export async function shareExportFile(html: string, filename: string, title?: string): Promise<ShareResult> {
  try {
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const file = new File([blob], filename, { type: 'text/html' });

    const nav = navigator as Navigator & {
      canShare?: (data: { files?: File[] }) => boolean;
      share?: (data: { files?: File[]; title?: string; text?: string }) => Promise<void>;
    };

    // Preferred: share the file via the native share sheet.
    if (typeof nav.share === 'function') {
      const canShareFiles = typeof nav.canShare === 'function'
        ? (() => { try { return nav.canShare!({ files: [file] }); } catch { return false; } })()
        : true; // assume yes if canShare not implemented; share() will reject if not supported

      if (canShareFiles) {
        try {
          await nav.share({ files: [file], title: title || filename });
          return 'shared';
        } catch (e: unknown) {
          const err = e as Error;
          if (err?.name === 'AbortError') return 'cancelled';
          // Non-abort error: fall through to download fallback below.
        }
      }
    }

    // Fallback: trigger a download so the user can attach it manually.
    try {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.style.display = 'none';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 5000);
      return 'downloaded';
    } catch {
      return 'failed';
    }
  } catch {
    return 'failed';
  }
}
