/**
 * Share an exported HTML document via the native share sheet.
 *
 * Uses Web Share Level 2 (files) when available so the user can route the
 * document to Mail, Messages, Drive, etc. Falls back to a plain anchor
 * download when the platform cannot share files.
 *
 * Important:
 *  - This does NOT send anything from the backend.
 *  - This does NOT create any "send" log or record.
 *  - The HTML is generated by the existing locked export renderer.
 */

export type ShareResult = 'shared' | 'cancelled' | 'downloaded' | 'unsupported' | 'failed';

export async function shareExportFile(html: string, filename: string, title?: string): Promise<ShareResult> {
  try {
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const file = new File([blob], filename, { type: 'text/html' });

    const nav = navigator as Navigator & {
      canShare?: (data: { files?: File[] }) => boolean;
      share?: (data: { files?: File[]; title?: string; text?: string }) => Promise<void>;
    };

    if (nav.share && nav.canShare?.({ files: [file] })) {
      try {
        await nav.share({ files: [file], title: title || filename });
        return 'shared';
      } catch (e: unknown) {
        const err = e as Error;
        if (err?.name === 'AbortError') return 'cancelled';
        // Fall through to download fallback.
      }
    }

    // Fallback: trigger a download so the user can attach it manually.
    try {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      a.style.display = 'none';
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      setTimeout(() => URL.revokeObjectURL(url), 5000);
      return 'downloaded';
    } catch {
      return 'failed';
    }
  } catch {
    return 'failed';
  }
}
