// Phase 6D — source-agnostic My Record "Configure" panel.
import { typeLabel, type AttachmentType } from '../media/mediaCore';
import { DEFAULT_DOSSIER_TITLE, type DossierConfig } from './dossierModel';
export interface ConfigureRow { id: string; label: string; meta: string; included: boolean; }
interface Props { cfg: DossierConfig; onChange: (next: DossierConfig) => void; rows: ConfigureRow[]; totalRecords: number; categories: string[]; people: string[]; onToggleMember: (id: string, included: boolean) => void; totalMembers: number; hiddenByFilters: number; includedInDocument: number; evidenceNote?: string; supportsHistory?: boolean; supportsEvidence?: boolean; busyId?: string | null; }
const DEFAULT_EVIDENCE_NOTE = 'Evidence always belongs to its record. If a record is not included, none of its evidence appears. No attachment-type selection means all types are included.';
const DossierConfigureView = ({ cfg, onChange, rows, totalRecords, categories, people, onToggleMember, totalMembers, hiddenByFilters, includedInDocument, evidenceNote, supportsHistory = true, supportsEvidence = true, busyId = null }: Props) => {
  const set = (patch: Partial<DossierConfig>) => onChange({ ...cfg, ...patch });
  const activeFilterCount = [cfg.from, cfg.to, cfg.category, cfg.person].filter(Boolean).length; const filtersActive = activeFilterCount > 0;
  const pressed = (on: boolean, label: string, action: () => void, key?: string) => <button key={key ?? label} type="button" className="proto-selchip" data-on={on} aria-pressed={on} onClick={action}>{label}</button>;
  return <div className="proto-noprint">
    <section className="proto-fgroup" aria-labelledby="report-title-label"><h2 id="report-title-label" className="proto-flabel">Report title</h2><input aria-labelledby="report-title-label" className="proto-input" value={cfg.title} placeholder={DEFAULT_DOSSIER_TITLE} onChange={e => set({ title: e.target.value })} /></section>
    <section className="proto-fgroup" aria-labelledby="report-order-label"><h2 id="report-order-label" className="proto-flabel">Order</h2><div className="proto-chipwrap">{pressed(cfg.order === 'asc', 'Oldest first', () => set({ order: 'asc' }))}{pressed(cfg.order === 'desc', 'Newest first', () => set({ order: 'desc' }))}</div></section>
    <section className="proto-fgroup" data-guide="chronicle-options" aria-labelledby="report-contents-label"><h2 id="report-contents-label" className="proto-flabel">What the report contains</h2><div className="proto-chipwrap">
      {pressed(cfg.includeDetails, 'Organisational details', () => set({ includeDetails: !cfg.includeDetails }))}{pressed(cfg.includeClarifications, 'Clarifications', () => set({ includeClarifications: !cfg.includeClarifications }))}{supportsHistory && pressed(cfg.includeHistory, 'Record history', () => set({ includeHistory: !cfg.includeHistory }))}
    </div><p className="proto-help">Organisational details cover the event date, category, context and people recorded. These settings change how the report reads, not which records belong to your Chronicle.</p></section>
    {supportsEvidence && <section className="proto-fgroup" aria-labelledby="report-evidence-label"><h2 id="report-evidence-label" className="proto-flabel">Evidence</h2><div className="proto-chipwrap">{pressed(cfg.includeVoice, 'Voice-record references', () => set({ includeVoice: !cfg.includeVoice }))}{pressed(cfg.includeAttachments, 'Attachments', () => set({ includeAttachments: !cfg.includeAttachments }))}</div>
      {cfg.includeAttachments && <div className="proto-chipwrap" style={{ marginTop: 8 }}>{(['image', 'document', 'audio', 'video', 'other'] as AttachmentType[]).map(t => pressed(cfg.attachmentTypes.includes(t), typeLabel[t], () => set({ attachmentTypes: cfg.attachmentTypes.includes(t) ? cfg.attachmentTypes.filter(x => x !== t) : [...cfg.attachmentTypes, t] }), t))}</div>}<p className="proto-help">{evidenceNote ?? DEFAULT_EVIDENCE_NOTE}</p></section>}
    <section className="proto-fgroup" data-guide="chronicle-filters" data-filters-active={filtersActive} aria-labelledby="report-filter-label"><div className="proto-filterhead"><h2 id="report-filter-label" className="proto-flabel proto-filterhead-title">Filter records</h2>{filtersActive && <span className="proto-filterbadge" data-testid="chronicle-filter-count" role="status">{activeFilterCount} active {activeFilterCount === 1 ? 'filter' : 'filters'}</span>}</div><p className="proto-help" style={{ marginBottom: 8 }}>Filters help you find records. They never change your saved records.</p>
      <div className="proto-daterow"><label><span className="proto-help">From</span><input className="proto-input" type="date" value={cfg.from ?? ''} onChange={e => set({ from: e.target.value || null })} /></label><label><span className="proto-help">To</span><input className="proto-input" type="date" value={cfg.to ?? ''} onChange={e => set({ to: e.target.value || null })} /></label></div>
      {categories.length > 0 && <div className="proto-chipwrap" style={{ marginTop: 10 }} aria-label="Filter by category">{categories.map(c => pressed(cfg.category === c, c, () => set({ category: cfg.category === c ? null : c }), c))}</div>}
      {people.length > 0 && <div className="proto-chipwrap" style={{ marginTop: 8 }} aria-label="Filter by person">{people.map(p => pressed(cfg.person === p, p, () => set({ person: cfg.person === p ? null : p }), p))}</div>}
      {filtersActive && <button type="button" className="proto-btn" data-variant="ghost" style={{ marginTop: 10 }} data-testid="chronicle-clear-filters" onClick={() => set({ from: null, to: null, category: null, person: null })}>Clear filters</button>}<p className="proto-help">Filters decide which included records appear in this document. They never add or remove records from your Chronicle itself.</p></section>
    <section className="proto-fgroup" data-guide="chronicle-records" aria-labelledby="report-records-label"><h2 id="report-records-label" className="proto-flabel">Records</h2>{totalRecords === 0 ? <div className="proto-empty">No records yet.</div> : rows.length === 0 ? <div className="proto-empty">No records match the current scope. Clear the filters to see everything again.</div> : rows.map(r => <label key={r.id} className="proto-selectrow"><input type="checkbox" checked={r.included} disabled={busyId === r.id} onChange={ev => onToggleMember(r.id, ev.target.checked)} /><span><span className="proto-selectrow-title">{r.label}</span><span className="proto-help">{r.meta}</span></span></label>)}</section>
    <p className="proto-help" role="status">{totalMembers} record{totalMembers === 1 ? '' : 's'} in your Chronicle{hiddenByFilters > 0 ? ` · ${hiddenByFilters} outside the current scope` : ''}{includedInDocument === 1 ? ' · this report contains a single record' : ''}.</p>
  </div>;
};
export default DossierConfigureView;
