// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-incidents.ts
import { createClient } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_incidents_default = defineTool({
  name: "list_incidents",
  title: "List incidents",
  description: "List the signed-in user's recorded workplace incidents in reverse chronological order (most recent incident_date first). Returns id, title, incident_date, category, subtype, severity, and a short summary. Does not return raw narrative or attachments.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(25).describe("Maximum number of incidents to return (1-100)."),
    category: z.string().optional().describe("Optional exact category filter, e.g. 'Communication'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("incidents").select("id, title, incident_date, category, subtype, severity, ai_summary, created_at").order("incident_date", { ascending: false, nullsFirst: false }).order("created_at", { ascending: false }).limit(limit);
    if (category) query = query.eq("category", category);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { incidents: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-incident.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_incident_default = defineTool2({
  name: "get_incident",
  title: "Get incident",
  description: "Fetch a single incident record belonging to the signed-in user by its id. Returns the full incident row including raw_narrative and ai_summary.",
  inputSchema: {
    id: z2.string().uuid().describe("Incident UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("incidents").select("*").eq("id", id).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    if (!data) {
      return { content: [{ type: "text", text: "Incident not found" }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { incident: data }
    };
  }
});

// src/lib/mcp/tools/create-incident.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.99.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_incident_default = defineTool3({
  name: "create_incident",
  title: "Create incident record",
  description: "Create a new workplace incident record for the signed-in user. The user's own words are preserved verbatim in raw_narrative \u2014 do not paraphrase. Optional structured fields (title, incident_date, location, people_involved, category) may be supplied when clearly stated by the user; leave them blank otherwise.",
  inputSchema: {
    raw_narrative: z3.string().trim().min(1).describe("The user's account of the incident, preserved verbatim in their own words."),
    title: z3.string().trim().min(1).max(200).optional().describe("Short title for the record."),
    incident_date: z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().describe("Date the incident occurred, YYYY-MM-DD."),
    location: z3.string().trim().optional().describe("Where the incident took place."),
    people_involved: z3.array(z3.string().trim().min(1)).optional().describe("Names of people involved."),
    category: z3.string().trim().optional().describe("Primary category, if clearly stated.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const row = {
      user_id: ctx.getUserId(),
      raw_narrative: input.raw_narrative,
      title: input.title ?? null,
      incident_date: input.incident_date ?? null,
      location: input.location ?? null,
      people_involved: input.people_involved ?? null,
      category: input.category ?? null,
      record_method: "mcp",
      status: "draft"
    };
    const { data, error } = await supabaseForUser3(ctx).from("incidents").insert(row).select("id, title, incident_date, category, created_at").single();
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [
        { type: "text", text: `Incident recorded (id: ${data.id}). Review it in Chronicle before finalising.` }
      ],
      structuredContent: { incident: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qjwrnrvzdnyyrtwvrbem";
var mcp_default = defineMcp({
  name: "project-chronicle-mcp",
  title: "Project Chronicle",
  version: "0.1.0",
  instructions: "Tools for Project Chronicle \u2014 a structured, chronological workplace record. Use `list_incidents` to browse the signed-in user's recorded incidents, `get_incident` to read a specific record in full, and `create_incident` to add a new record. Preserve the user's own words verbatim in raw_narrative; never paraphrase or add legal interpretation.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_incidents_default, get_incident_default, create_incident_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
